name: Fetch QA info
run-name: ${{ github.actor }} has started the script

on: [workflow_dispatch]

jobs:
  main:
    name: qa_tickets_checker
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.2'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup checker
        uses: actions/checkout@v2

      - name: Run checker
        run: python3 main.py

#        env:
#          JIRA_MAIL: ${{ secrets.JIRA_MAIL }}
#          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
#
#          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
#
#          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
#          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
#
#          SHAREPOINT_SITE_NAME: ${{ secrets.SHAREPOINT_SITE_NAME }}
#          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
#          SHAREPOINT_DOC: ${{ secrets.SHAREPOINT_DOC }}
#          SHAREPOINT_FOLDER_NAME: ${{ secrets.SHAREPOINT_FOLDER_NAME }}
#
#          FILE_NAME: ${{ secrets.FILE_NAME }}
#          LOCAL_FOLDER: ${{ secrets.LOCAL_FOLDER }}
