name: Fetch QA info
run-name: Started by ${{ github.event_type }}

on:
  repository_dispatch:
    types: test

jobs:
  main:
    name: qa_tickets_checker
    runs-on: ubuntu-latest
    steps:
      - name: Setup checker
        uses: actions/checkout@v3

      - name: Setup Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
          architecture: "x64"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker
#        env:
#          VALUE_TEST: ${{ secrets.VALUE_TEST }}

        run: python3 src/main.py