name: Fetch QA info
run-name: ${{ github.actor }} has started the script

on: [workflow_dispatch]

jobs:
  main:
    name: qa_tickets_checker
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.2'

      - name: Setup checker
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker
        env:
          VALUE_TEST: ${{ secrets.VALUE_TEST }}
#          JIRA_MAIL: ${{ secrets.JIRA_MAIL }}
#          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
#
#          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
#
#          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
#          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
#
        run: python3 main.py
